#! /usr/bin/perl

unless (@ARGV) { print STDERR "Usage: cbe_run command\n"; exit(0); }

@run = (1..32);
#@run = (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32);
$user = `whoami`;
chomp $user;
if ($ARGV[0] eq "-r") {
    $user = "root";
    shift @ARGV;
}

foreach $i (@run) {
    $node = sprintf("cbe-node-%02d", $i);
    $cmd = "ssh -nxf -l $user $node 'source /opt/cbe-local/yuppi/pulsar_env.csh; @ARGV'";
    print "# $node:\n";
    #print $cmd . "\n";
    system($cmd);
}
