#! /bin/bash
source /opt/cbe-local/yuppi/pulsar_env.bash

echo "yuppi_init_all " `date` >> $PSRLOGS/yuppi_init.`hostname`.log

# Clear old shared mem buffers
clean_guppi_shmem

# Init new shared mem buffers
check_guppi_status > /dev/null 2>>$PSRLOGS/yuppi_init.`hostname`.log
check_guppi_databuf -c -i1 -n8 -s128 > /dev/null 2>>$PSRLOGS/yuppi_init.`hostname`.log

# Set up basic info in status shared mem
guppi_set_params --force --evla --src="Init" --freq=1400 --ra=00:00:00.0 --dec=+00:00:00.0

# Start guppi_daq_server in background
( guppi_daq_server >> $PSRLOGS/guppi_daq_server.`hostname`.`date +%Y%m%d`.log 2>&1 ) & 

# Start packet-sniffer
( $PSR/src/EVLA_pulsars/multicast/async_mcast.py >> $PSRLOGS/async_mcast.`hostname`.`date +%Y%m%d`.log 2>&1 ) &
